"""
    input/output related constants
"""

SECRET_ENV_VAR_NAME = "SECRET_EXPENSOR"

VAR_DROPBOX_TOKEN = "EXPENSOR_DROPBOX_TOKEN"
VAR_USER = "EXPENSOR_USER"
VAR_PASSWORD = "EXPENSOR_PASSWORD"

PATH_MONEY_LOVER = "/Money Lover/"
FILE_DATA = "/data.xlsx"
FILE_CONFIG = "/config.yml"
FILE_SECRETS = "secrets.yaml"

FORBIDDEN_CATEGORIES = ["Debt", "Loan"]
